app_login:
    path: /login
    controller: App\Controller\SecurityController::login

login_check:
    path: /login_check
    
_security_logout:
    resource: security.route_loader.logout
    type: service
